CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
SIMILAR_DOCUMENTS = 10
EMBEDDING_MODEL = "models/embedding-001"
LLM_MODEL = "gemini-1.5-flash"

FILE_EXTENSION_OPTIONS = ["pdf", "docx", "txt", "pptx", "xlsx"]
MAX_NO_OF_YOUTUBE_URL = 3
MAX_NO_OF_WEBSITE_URL = 5
FILE_UPLOAD_DIRECTORY = "uploads"

CHAT_USER_ICON = "🧑"
CHAT_AI_ICON = "🤖"